### ISSUE TITLE
oauth?  #feature request

### ISSUE THREAD

**Issue by hye** [wizjin/weixin#13]
http://mp.weixin.qq.com/wiki/index.php?title=%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF

**Comment by wizjin** [comment]
Please see version 0.5.2. Thanks.
