### ISSUE TITLE
downloadMedia

### ISSUE THREAD

**Issue by take7yo** [wizjin/weixin#17]
多媒体文件下载的时候 Content-Type: text/plain以外的情况下:
只返回r.Body(其他类型的处理好像也都是只返回r.Body).
同样的是多媒体类型之图片的时候,没法判断获取的内容是什么类型的文件.
比如jpg/png就无法区分,但是又要在开始的时候创建文件.

**Comment by wizjin** [comment]
可以试一下，`net/http`包里面的[DetectContentType](https://golang.org/pkg/net/http/#DetectContentType)。
