### ISSUE TITLE
Can't create menu when using openauth url with "&"

### ISSUE THREAD

**Issue by imzjy** [wizjin/weixin#18]
Json lib will encoding the "&" to \u0026 , so if you want to create openauth url like:
`https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect `
That will cause the CreateMenu fail.

The related code:
https://github.com/wizjin/weixin/blob/master/weixin.go#L418

I've got quick-and-dirty patch by repalce it to "&"
https://github.com/imzjy/weixin/blob/master/weixin.go#L391

Maybe there is good way to fix it, just hightlight the issue here.

**Comment by wizjin** [comment]
是否可以试一下使用微信公共平台里面的短地址功能呢？
https://github.com/wizjin/weixin/blob/master/weixin.go#L392
