### ISSUE TITLE
不支持AES加密吗?

### ISSUE THREAD

**Issue by botvs** [wizjin/weixin#24]
不支持aes加密吗?

**Comment by wizjin** [comment]
嗯嗯！加密的还没来的及做！最近比较忙！@。@

**Comment by zeropool** [comment]
很喜欢这个库,All in one, 希望有空了能支持AES加密

**Comment by wizjin** [comment]
谢谢支持，我看看，下周如果空的话，抽时间加一下AES加密！呵呵！:)
