### ISSUE TITLE
Token的存储和共享问题

### ISSUE THREAD

**Issue by uliian** [wizjin/weixin#28]
在集群环境下，Token是需要进行集中化管理的，而现在的这种模式，我觉得做集中化管理比较困难把~能不能有办法解决呢？

**Comment by wizjin** [comment]
的确，现在这个库设计的时候主要考虑使用方便，并没有考虑到集群的问题。
可选的解决方案是提供一个配置项，例如一个Channel，这个库从这个Channel获取Token。
这样一来这个库本身放弃对token的管理，由一个专门的服务提供统一集中化的Token管理功能。

**Comment by sunanxiang** [comment]
accessToken 是这么获取的吗？微信官方文档不是需要调用接口吗？我看你这里用原子操作自己写入的？不太懂，求解

**Comment by qianlongzt** [comment]
`func (wx *Weixin) GetAccessToken() AccessToken` 应该返回个 error，不然只能用 token 字符串是否为空 判断是否发生错误。

**Comment by wizjin** [comment]
AccessToken里面本来就有过期时间，利用的的是过期时间来判断是否可用，出错时候返回的过期时间是0，就是一定会过期，和token 字符串是否为空没有关系。而且过期时间是一定要判断的，所以感觉没有必要暴露这个error，而且整个access token获取过程都在包内部，返回error感觉也无助于解决问题。

**Comment by qianlongzt** [comment]
嗯，好的。
